name: Deployment

on:
  push:
    branches: [master] # push events on source branch master push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Run Build
      run: |
        npm install
        npm run build
        ls dist/

    - name: Deploy
      run: cd dist/
      uses: up9cloud/action-rsync@master
      env:
        USER: ${{secrets.RSYNC_USER}}
        HOST: ${{secrets.RSYNC_HOST}}
        KEY: ${{secrets.RSYNC_KEY}}
        ARGS: -av --delete
        SOURCE: ./
        TARGET: ${{secrets.RSYNC_DIR}}